In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from sklearn.compose import ColumnTransformer

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
from sklearn.impute import SimpleImputer

In [6]:
from sklearn.preprocessing import OneHotEncoder

In [7]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import r2_score


In [8]:
from sklearn.pipeline import Pipeline,make_pipeline

In [9]:
from sklearn.feature_selection import SelectKBest,chi2

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
#loading dataset

In [12]:
df=pd.read_csv("Downloads\CAR PRICE PREDICTION WITH MACHINE LEARNING.CSV")

In [13]:
df

car_ID  symboling                   CarName fueltype aspiration  \
0         1          3        alfa-romero giulia      gas        std   
1         2          3       alfa-romero stelvio      gas        std   
2         3          1  alfa-romero Quadrifoglio      gas        std   
3         4          2               audi 100 ls      gas        std   
4         5          2                audi 100ls      gas        std   
..      ...        ...                       ...      ...        ...   
200     201         -1           volvo 145e (sw)      gas        std   
201     202         -1               volvo 144ea      gas      turbo   
202     203         -1               volvo 244dl      gas        std   
203     204         -1                 volvo 246   diesel      turbo   
204     205         -1               volvo 264gl      gas      turbo   

    doornumber      carbody drivewheel enginelocation  wheelbase  ...  \
0          two  convertible        rwd          front       88.6  ...   
1          two  convertible        rwd          front       88.6  ...   
2          two    hatchback        rwd          front       94.5  ...   
3         four        sedan        fwd          front       99.8  ...   
4         four        sedan        4wd          front       99.4  ...   
..         ...          ...        ...            ...        ...  ...   
200       four        sedan        rwd          front      109.1  ...   
201       four        sedan        rwd          front      109.1  ...   
202       four        sedan        rwd          front      109.1  ...   
203       four        sedan        rwd          front      109.1  ...   
204       four        sedan        rwd          front      109.1  ...   

     enginesize  fuelsystem  boreratio  stroke compressionratio horsepower  \
0           130        mpfi       3.47    2.68              9.0        111   
1           130        mpfi       3.47    2.68              9.0        111   
2           152        mpfi       2.68    3.47              9.0        154   
3           109        mpfi       3.19    3.40             10.0        102   
4           136        mpfi       3.19    3.40              8.0        115   
..          ...         ...        ...     ...              ...        ...   
200         141        mpfi       3.78    3.15              9.5        114   
201         141        mpfi       3.78    3.15              8.7        160   
202         173        mpfi       3.58    2.87              8.8        134   
203         145         idi       3.01    3.40             23.0        106   
204         141        mpfi       3.78    3.15              9.5        114   

     peakrpm citympg  highwaympg    price  
0       5000      21          27  13495.0  
1       5000      21          27  16500.0  
2       5000      19          26  16500.0  
3       5500      24          30  13950.0  
4       5500      18          22  17450.0  
..       ...     ...         ...      ...  
200     5400      23          28  16845.0  
201     5300      19          25  19045.0  
202     5500      18          23  21485.0  
203     4800      26          27  22470.0  
204     5400      19          25  22625.0  

[205 rows x 26 columns]

In [14]:
df.describe()

car_ID   symboling   wheelbase   carlength    carwidth   carheight  \
count  205.000000  205.000000  205.000000  205.000000  205.000000  205.000000   
mean   103.000000    0.834146   98.756585  174.049268   65.907805   53.724878   
std     59.322565    1.245307    6.021776   12.337289    2.145204    2.443522   
min      1.000000   -2.000000   86.600000  141.100000   60.300000   47.800000   
25%     52.000000    0.000000   94.500000  166.300000   64.100000   52.000000   
50%    103.000000    1.000000   97.000000  173.200000   65.500000   54.100000   
75%    154.000000    2.000000  102.400000  183.100000   66.900000   55.500000   
max    205.000000    3.000000  120.900000  208.100000   72.300000   59.800000   

        curbweight  enginesize   boreratio      stroke  compressionratio  \
count   205.000000  205.000000  205.000000  205.000000        205.000000   
mean   2555.565854  126.907317    3.329756    3.255415         10.142537   
std     520.680204   41.642693    0.270844    0.313597          3.972040   
min    1488.000000   61.000000    2.540000    2.070000          7.000000   
25%    2145.000000   97.000000    3.150000    3.110000          8.600000   
50%    2414.000000  120.000000    3.310000    3.290000          9.000000   
75%    2935.000000  141.000000    3.580000    3.410000          9.400000   
max    4066.000000  326.000000    3.940000    4.170000         23.000000   

       horsepower      peakrpm     citympg  highwaympg         price  
count  205.000000   205.000000  205.000000  205.000000    205.000000  
mean   104.117073  5125.121951   25.219512   30.751220  13276.710571  
std     39.544167   476.985643    6.542142    6.886443   7988.852332  
min     48.000000  4150.000000   13.000000   16.000000   5118.000000  
25%     70.000000  4800.000000   19.000000   25.000000   7788.000000  
50%     95.000000  5200.000000   24.000000   30.000000  10295.000000  
75%    116.000000  5500.000000   30.000000   34.000000  16503.000000  
max    288.000000  6600.000000   49.000000   54.000000  45400.000000

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   car_ID            205 non-null    int64  
 1   symboling         205 non-null    int64  
 2   CarName           205 non-null    object 
 3   fueltype          205 non-null    object 
 4   aspiration        205 non-null    object 
 5   doornumber        205 non-null    object 
 6   carbody           205 non-null    object 
 7   drivewheel        205 non-null    object 
 8   enginelocation    205 non-null    object 
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64  
 14  enginetype        205 non-null    object 
 15  cylindernumber    205 non-null    object 
 16  enginesize        205 non-null    int64  
 1

In [16]:
#getting attribute name

In [17]:
df.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [18]:
#checking duplicates

In [19]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
200    False
201    False
202    False
203    False
204    False
Length: 205, dtype: bool

In [20]:
#removing of unwanted columns

In [21]:
df=df.drop(columns=['car_ID','symboling','CarName'])
df

fueltype aspiration doornumber      carbody drivewheel enginelocation  \
0        gas        std        two  convertible        rwd          front   
1        gas        std        two  convertible        rwd          front   
2        gas        std        two    hatchback        rwd          front   
3        gas        std       four        sedan        fwd          front   
4        gas        std       four        sedan        4wd          front   
..       ...        ...        ...          ...        ...            ...   
200      gas        std       four        sedan        rwd          front   
201      gas      turbo       four        sedan        rwd          front   
202      gas        std       four        sedan        rwd          front   
203   diesel      turbo       four        sedan        rwd          front   
204      gas      turbo       four        sedan        rwd          front   

     wheelbase  carlength  carwidth  carheight  ...  enginesize fuelsystem  \
0         88.6      168.8      64.1       48.8  ...         130       mpfi   
1         88.6      168.8      64.1       48.8  ...         130       mpfi   
2         94.5      171.2      65.5       52.4  ...         152       mpfi   
3         99.8      176.6      66.2       54.3  ...         109       mpfi   
4         99.4      176.6      66.4       54.3  ...         136       mpfi   
..         ...        ...       ...        ...  ...         ...        ...   
200      109.1      188.8      68.9       55.5  ...         141       mpfi   
201      109.1      188.8      68.8       55.5  ...         141       mpfi   
202      109.1      188.8      68.9       55.5  ...         173       mpfi   
203      109.1      188.8      68.9       55.5  ...         145        idi   
204      109.1      188.8      68.9       55.5  ...         141       mpfi   

    boreratio  stroke compressionratio  horsepower  peakrpm  citympg  \
0        3.47    2.68              9.0         111     5000       21   
1        3.47    2.68              9.0         111     5000       21   
2        2.68    3.47              9.0         154     5000       19   
3        3.19    3.40             10.0         102     5500       24   
4        3.19    3.40              8.0         115     5500       18   
..        ...     ...              ...         ...      ...      ...   
200      3.78    3.15              9.5         114     5400       23   
201      3.78    3.15              8.7         160     5300       19   
202      3.58    2.87              8.8         134     5500       18   
203      3.01    3.40             23.0         106     4800       26   
204      3.78    3.15              9.5         114     5400       19   

     highwaympg    price  
0            27  13495.0  
1            27  16500.0  
2            26  16500.0  
3            30  13950.0  
4            22  17450.0  
..          ...      ...  
200          28  16845.0  
201          25  19045.0  
202          23  21485.0  
203          27  22470.0  
204          25  22625.0  

[205 rows x 23 columns]

In [22]:
#dependent and independent variables
x=df.iloc[:,:22]
y=df.iloc[:,22]

In [23]:
#splitting of training and testing data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [24]:
x_train

fueltype aspiration doornumber    carbody drivewheel enginelocation  \
177      gas        std       four  hatchback        fwd          front   
75       gas      turbo        two  hatchback        rwd          front   
174   diesel      turbo       four      sedan        fwd          front   
31       gas        std        two  hatchback        fwd          front   
12       gas        std        two      sedan        rwd          front   
..       ...        ...        ...        ...        ...            ...   
106      gas        std        two  hatchback        rwd          front   
14       gas        std       four      sedan        rwd          front   
92       gas        std       four      sedan        fwd          front   
179      gas        std        two  hatchback        rwd          front   
102      gas        std       four      wagon        fwd          front   

     wheelbase  carlength  carwidth  carheight  ...  cylindernumber  \
177      102.4      175.6      66.5       53.9  ...            four   
75       102.7      178.4      68.0       54.8  ...            four   
174      102.4      175.6      66.5       54.9  ...            four   
31        86.6      144.6      63.9       50.8  ...            four   
12       101.2      176.8      64.8       54.3  ...             six   
..         ...        ...       ...        ...  ...             ...   
106       99.2      178.5      67.9       49.7  ...             six   
14       103.5      189.0      66.9       55.7  ...             six   
92        94.5      165.3      63.8       54.5  ...            four   
179      102.9      183.5      67.7       52.0  ...             six   
102      100.4      184.6      66.5       56.1  ...             six   

    enginesize fuelsystem  boreratio stroke  compressionratio  horsepower  \
177        122       mpfi       3.31   3.54               8.7          92   
75         140       mpfi       3.78   3.12               8.0         175   
174        110        idi       3.27   3.35              22.5          73   
31          92       1bbl       2.91   3.41               9.2          76   
12         164       mpfi       3.31   3.19               9.0         121   
..         ...        ...        ...    ...               ...         ...   
106        181       mpfi       3.43   3.27               9.0         160   
14         164       mpfi       3.31   3.19               9.0         121   
92          97       2bbl       3.15   3.29               9.4          69   
179        171       mpfi       3.27   3.35               9.3         161   
102        181       mpfi       3.43   3.27               9.0         152   

     peakrpm  citympg  highwaympg  
177     4200       27          32  
75      5000       19          24  
174     4500       30          33  
31      6000       31          38  
12      4250       21          28  
..       ...      ...         ...  
106     5200       19          25  
14      4250       20          25  
92      5200       31          37  
179     5200       19          24  
102     5200       17          22  

[143 rows x 22 columns]

In [25]:
x_test
y_train

177    11248.0
75     16503.0
174    10698.0
31      6855.0
12     20970.0
        ...   
106    18399.0
14     24565.0
92      6849.0
179    15998.0
102    14399.0
Name: price, Length: 143, dtype: float64

In [26]:
df.isnull().sum()

fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [27]:
#OneHotEncoding

In [28]:
ohe=OneHotEncoder(drop="first",sparse=False,handle_unknown='ignore')
x_train_new=ohe.fit_transform(x_train[['fueltype','aspiration','doornumber','carbody','drivewheel','enginelocation','enginetype','cylindernumber','fuelsystem']])
x_test_new=ohe.transform(x_test[['fueltype','aspiration','doornumber','carbody','drivewheel','enginelocation','enginetype','cylindernumber','fuelsystem']])

C:\Users\J. SHIVANI\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:170: UserWarning: Found unknown categories in columns [7, 8] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(


In [29]:
df['wheelbase'] = df['wheelbase'].astype(int)
df['carlength'] = df['carlength'].astype(int)
df['carwidth'] = df['carwidth'].astype(int)
df['carheight'] = df['carheight'].astype(int)
df['boreratio'] = df['boreratio'].astype(int)
df['stroke'] = df['stroke'].astype(int)
df['compressionratio'] = df['compressionratio'].astype(int)

In [30]:
x_train_new

array([[1., 0., 0., ..., 1., 0., 0.],
       [1., 1., 1., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.]])

In [31]:
x_test_new

array([[1., 0., 0., ..., 1., 0., 0.],
       [1., 1., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 1., 0., 0.]])

In [32]:
x_train_new1=x_train.drop(columns=['fueltype','aspiration','doornumber','carbody','drivewheel','enginelocation','enginetype','cylindernumber','fuelsystem']).values

In [33]:
x_test_new1=x_test.drop(columns=['fueltype','aspiration','doornumber','carbody','drivewheel','enginelocation','enginetype','cylindernumber','fuelsystem']).values

In [34]:
x_train_new1

array([[ 102.4,  175.6,   66.5, ..., 4200. ,   27. ,   32. ],
       [ 102.7,  178.4,   68. , ..., 5000. ,   19. ,   24. ],
       [ 102.4,  175.6,   66.5, ..., 4500. ,   30. ,   33. ],
       ...,
       [  94.5,  165.3,   63.8, ..., 5200. ,   31. ,   37. ],
       [ 102.9,  183.5,   67.7, ..., 5200. ,   19. ,   24. ],
       [ 100.4,  184.6,   66.5, ..., 5200. ,   17. ,   22. ]])

In [35]:
x_test_new1

array([[1.035e+02, 1.890e+02, 6.690e+01, 5.570e+01, 3.230e+03, 2.090e+02,
        3.620e+00, 3.390e+00, 8.000e+00, 1.820e+02, 5.400e+03, 1.600e+01,
        2.200e+01],
       [9.950e+01, 1.782e+02, 6.790e+01, 5.200e+01, 3.053e+03, 1.310e+02,
        3.130e+00, 3.400e+00, 7.000e+00, 1.600e+02, 5.500e+03, 1.600e+01,
        2.200e+01],
       [9.720e+01, 1.734e+02, 6.520e+01, 5.470e+01, 2.302e+03, 1.200e+02,
        3.330e+00, 3.470e+00, 8.500e+00, 9.700e+01, 5.200e+03, 2.700e+01,
        3.400e+01],
       [9.910e+01, 1.866e+02, 6.650e+01, 5.610e+01, 2.658e+03, 1.210e+02,
        3.540e+00, 3.070e+00, 9.310e+00, 1.100e+02, 5.250e+03, 2.100e+01,
        2.800e+01],
       [1.100e+02, 1.909e+02, 7.030e+01, 5.870e+01, 3.750e+03, 1.830e+02,
        3.580e+00, 3.640e+00, 2.150e+01, 1.230e+02, 4.350e+03, 2.200e+01,
        2.500e+01],
       [9.450e+01, 1.656e+02, 6.380e+01, 5.330e+01, 2.028e+03, 9.700e+01,
        3.150e+00, 3.290e+00, 9.400e+00, 6.900e+01, 5.200e+03, 3.100e+01,
        3.70

In [36]:
x_train_new1

array([[ 102.4,  175.6,   66.5, ..., 4200. ,   27. ,   32. ],
       [ 102.7,  178.4,   68. , ..., 5000. ,   19. ,   24. ],
       [ 102.4,  175.6,   66.5, ..., 4500. ,   30. ,   33. ],
       ...,
       [  94.5,  165.3,   63.8, ..., 5200. ,   31. ,   37. ],
       [ 102.9,  183.5,   67.7, ..., 5200. ,   19. ,   24. ],
       [ 100.4,  184.6,   66.5, ..., 5200. ,   17. ,   22. ]])

In [37]:
x_test_new1

array([[1.035e+02, 1.890e+02, 6.690e+01, 5.570e+01, 3.230e+03, 2.090e+02,
        3.620e+00, 3.390e+00, 8.000e+00, 1.820e+02, 5.400e+03, 1.600e+01,
        2.200e+01],
       [9.950e+01, 1.782e+02, 6.790e+01, 5.200e+01, 3.053e+03, 1.310e+02,
        3.130e+00, 3.400e+00, 7.000e+00, 1.600e+02, 5.500e+03, 1.600e+01,
        2.200e+01],
       [9.720e+01, 1.734e+02, 6.520e+01, 5.470e+01, 2.302e+03, 1.200e+02,
        3.330e+00, 3.470e+00, 8.500e+00, 9.700e+01, 5.200e+03, 2.700e+01,
        3.400e+01],
       [9.910e+01, 1.866e+02, 6.650e+01, 5.610e+01, 2.658e+03, 1.210e+02,
        3.540e+00, 3.070e+00, 9.310e+00, 1.100e+02, 5.250e+03, 2.100e+01,
        2.800e+01],
       [1.100e+02, 1.909e+02, 7.030e+01, 5.870e+01, 3.750e+03, 1.830e+02,
        3.580e+00, 3.640e+00, 2.150e+01, 1.230e+02, 4.350e+03, 2.200e+01,
        2.500e+01],
       [9.450e+01, 1.656e+02, 6.380e+01, 5.330e+01, 2.028e+03, 9.700e+01,
        3.150e+00, 3.290e+00, 9.400e+00, 6.900e+01, 5.200e+03, 3.100e+01,
        3.70

In [38]:
x_train_transformed=np.concatenate((x_train_new,x_train_new1),axis=1)

In [39]:
x_test_transformed=np.concatenate((x_test_new,x_test_new1),axis=1)

In [40]:
x_train_transformed.shape

(143, 40)

In [41]:
x_test_transformed.shape

(62, 40)

In [42]:
from sklearn.compose import ColumnTransformer

In [43]:
transformer=ColumnTransformer(transformers=[('tnf1',OneHotEncoder(sparse=False,drop="first",handle_unknown='ignore'),['fueltype','aspiration','doornumber','carbody','drivewheel','enginelocation','enginetype','cylindernumber','fuelsystem'])],remainder="passthrough")

In [44]:
transformer.fit_transform(x_train)

array([[1.0e+00, 0.0e+00, 0.0e+00, ..., 4.2e+03, 2.7e+01, 3.2e+01],
       [1.0e+00, 1.0e+00, 1.0e+00, ..., 5.0e+03, 1.9e+01, 2.4e+01],
       [0.0e+00, 1.0e+00, 0.0e+00, ..., 4.5e+03, 3.0e+01, 3.3e+01],
       ...,
       [1.0e+00, 0.0e+00, 0.0e+00, ..., 5.2e+03, 3.1e+01, 3.7e+01],
       [1.0e+00, 0.0e+00, 1.0e+00, ..., 5.2e+03, 1.9e+01, 2.4e+01],
       [1.0e+00, 0.0e+00, 0.0e+00, ..., 5.2e+03, 1.7e+01, 2.2e+01]])

In [45]:
transformer.transform(x_test)

C:\Users\J. SHIVANI\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:170: UserWarning: Found unknown categories in columns [7, 8] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(


array([[1.0e+00, 0.0e+00, 0.0e+00, ..., 5.4e+03, 1.6e+01, 2.2e+01],
       [1.0e+00, 1.0e+00, 1.0e+00, ..., 5.5e+03, 1.6e+01, 2.2e+01],
       [1.0e+00, 0.0e+00, 0.0e+00, ..., 5.2e+03, 2.7e+01, 3.4e+01],
       ...,
       [1.0e+00, 0.0e+00, 1.0e+00, ..., 5.5e+03, 3.7e+01, 4.1e+01],
       [1.0e+00, 0.0e+00, 0.0e+00, ..., 4.8e+03, 2.4e+01, 2.5e+01],
       [1.0e+00, 0.0e+00, 1.0e+00, ..., 5.2e+03, 1.9e+01, 2.5e+01]])

In [46]:
from sklearn.metrics import mean_squared_error


In [47]:
model=LinearRegression()
model.fit(x_train_transformed,y_train)
Y_pred=model.predict(x_test_transformed)
r2_score(y_test,Y_pred)*100

89.82986537068902